const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Plugins.Timeline,
		C3.Behaviors.Flash,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Arr.Exps.Back,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Cnds.OnSignal
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Touch: 0},
	{bg_kapak: 0},
	{btn_basla: 0},
	{btn_info: 0},
	{btn_Anasayfa: 0},
	{bg_info: 0},
	{btn_kaynakca: 0},
	{ornek_bg: 0},
	{Tween: 0},
	{etken_orn: 0},
	{edilgen_orn: 0},
	{btn_ileri: 0},
	{bg_oyun: 0},
	{Array_sorular: 0},
	{tenisciSol: 0},
	{tenisciSag: 0},
	{top: 0},
	{etkenSol: 0},
	{etkenSag: 0},
	{edilgenSol: 0},
	{edilgenSag: 0},
	{TimelineController: 0},
	{Flash: 0},
	{sorular: 0},
	{sayi1: 0},
	{sayi2: 0},
	{oyun1: 0},
	{oyun2: 0},
	{oyun3: 0},
	{oyun4: 0},
	{oyun5: 0},
	{oyun6: 0},
	{oyun11: 0},
	{oyun12: 0},
	{oyun13: 0},
	{oyun14: 0},
	{oyun15: 0},
	{oyun16: 0},
	{sure: 0},
	{sure2: 0},
	{Array_sagust: 0},
	{Array_sagAlt: 0},
	{Array_solBolge: 0},
	{bg_final: 0},
	{Audio: 0},
	{btn_ses: 0},
	{Sprite3: 0},
	{nasilOynanir: 0},
	{btn_nasilOynanir: 0},
	{buttons: 0},
	{info: 0},
	{posY: 0},
	{posX: 0},
	{posYY: 0},
	{dizi_sorular: 0},
	{sagUst: 0},
	{sagAlt: 0},
	{solBolge: 0},
	{tiklama: 0},
	{sureDegerlendir: 0},
	{puanSol: 0},
	{puanSag: 0},
	{frameTakip: 0},
	{tenisciHareket: 0},
	{sonuc: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	bg_kapak: class extends self.ISpriteInstance {},
	btn_basla: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	btn_Anasayfa: class extends self.ISpriteInstance {},
	bg_info: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	ornek_bg: class extends self.ISpriteInstance {},
	etken_orn: class extends self.ISpriteInstance {},
	edilgen_orn: class extends self.ISpriteInstance {},
	btn_ileri: class extends self.ISpriteInstance {},
	bg_oyun: class extends self.ISpriteInstance {},
	Array_sorular: class extends self.IArrayInstance {},
	tenisciSol: class extends self.ISpriteInstance {},
	tenisciSag: class extends self.ISpriteInstance {},
	top: class extends self.ISpriteInstance {},
	etkenSol: class extends self.ISpriteInstance {},
	etkenSag: class extends self.ISpriteInstance {},
	edilgenSol: class extends self.ISpriteInstance {},
	edilgenSag: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	sorular: class extends self.ISpriteInstance {},
	sayi1: class extends self.ISpriteInstance {},
	sayi2: class extends self.ISpriteInstance {},
	oyun1: class extends self.ISpriteInstance {},
	oyun2: class extends self.ISpriteInstance {},
	oyun3: class extends self.ISpriteInstance {},
	oyun4: class extends self.ISpriteInstance {},
	oyun5: class extends self.ISpriteInstance {},
	oyun6: class extends self.ISpriteInstance {},
	oyun11: class extends self.ISpriteInstance {},
	oyun12: class extends self.ISpriteInstance {},
	oyun13: class extends self.ISpriteInstance {},
	oyun14: class extends self.ISpriteInstance {},
	oyun15: class extends self.ISpriteInstance {},
	oyun16: class extends self.ISpriteInstance {},
	sure: class extends self.ISpriteInstance {},
	sure2: class extends self.ISpriteInstance {},
	Array_sagust: class extends self.IArrayInstance {},
	Array_sagAlt: class extends self.IArrayInstance {},
	Array_solBolge: class extends self.IArrayInstance {},
	bg_final: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	btn_ses: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	nasilOynanir: class extends self.ISpriteInstance {},
	btn_nasilOynanir: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {}
}